chat/urls.py
from django.urls import path
from .import views

app_name="chat"

urlpatterns=[
    path("<int:c_id>",views.Sentmessage,name="sentmsg")
]

posecollection/urls.py
from django.urls import path
from .import views

app_name="posecollection"

urlpatterns=[

    path('capture_pose', views.capture_pose, name='capture_pose'),
    path('inFrame', views.inFrame, name='inFrame'),
    path('train_model', views.train_model, name='train_model'),
    path('inf', views.inf, name='inf'),
    path('pose_list', views.pose_list, name='pose_list')
]

schedule/urls.py
from django.urls import path
from .import views

app_name="schedule"

urlpatterns=[
    path("allotclass/<slug:c_slug>",views.allotclass,name="allotclass"),
    path("coursedetails/<slug:c_slug>", views.coursedetails, name="coursedetails"),
    path("deleteclass/<int:id>", views.deleteclass, name="deleteclass"),
    path('live_classes/<int:c_id>', views.live_classes, name='live_classes'),
    path('mark_attendance/<int:class_schedule_id>/', views.mark_attendance, name='mark_attendance'),
    path('view_attendance/<int:class_schedule_id>/', views.view_attendance, name='view_attendance'),
    path('student_attendance/<int:c_id>', views.student_attendance, name='student_attendance'),
    path('attendance_graph/<int:c_id>/', views.attendance_graph, name='attendance_graph'),
    path('attendance_excel/<int:course_id>/<str:date>', views.attendance_excel, name='attendance_excel'),
    path('course_dates/<int:course_id>/', views.course_dates, name='course_dates'),
    path('generate_certificate/<int:course>', views.GeneratePdf,name="generate_certificate"),

]

yogaapp/urls.py
from django.urls import path
from . import views


app_name="yogaapp"

from django.contrib import admin
urlpatterns = [
    path('', views.index, name='index'),
    path('studentregistration', views.Studentregistration, name='studentregistration'),
    path('insrtructorregistration', views.insrtructorregistration, name='insrtructorregistration'),

    path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path("passwd_email",views.Passwdemail,name="passwd_email"),
    path('passwordreset/<uidb64>/<token>', views.Password_reset, name='password_reset'),

    path('login/', views.Login, name='login'),
    path('forgotpassword/<uidb64>', views.forgotpassword, name='forgotpassword'),

    path('studentdashboard', views.studentdashboard, name='studentdashboard'),
    path('studentdashboard/<slug:c_slug>', views.studentdashboard, name='studentdashboard'),
    path('studentdashboard/<slug:c_slug>/<slug:v_slug>', views.studentdashboard, name='studentdashboard'),

    path('salary/<int:salary_id>/', views.salary_details, name='salary_details'),
    path('pdf/<int:id>/', views.get,name='pdf'),
    path("progress/<int:progress>/<video>",views.Progress_update,name="Progress_update"),
    path("student_progress", views.Student_progress, name="student_progress"),

    path('logout', views.Logout, name='logout'),
    path('studentviewprofile', views.studentviewprofile, name='studentviewprofile'),
    path('studentupdate', views.studentupdate, name='studentupdate'),
    path('studentchangepassword', views.studentchangepassword, name='studentchangepassword'),
    # path('coursesenrolled', views.coursesenrolled, name='coursesenrolled'),
    path('availablecourses', views.availablecourses, name='availablecourses'),
    path('endroll/<slug:c_slug>', views.Course_endroll, name='endroll'),
    path('course/<slug:c_slug>/checkoutcourse/', views.checkoutcourse, name='checkoutcourse'),
    path('payment_done_course/', views.payment_done_course, name='payment_done_course'),
    path('aboutcourse/<int:c_id>/', views.aboutcourse, name='aboutcourse'),







    path('instructorviewvideos', views.instructorviewvideos, name='instructorviewvideos'),
    path('feedback', views.feedback, name='feedback'),

    # path('searchbar', views.searchbar, name='searchbar'),

    path('instructordashboard', views.instructordashboard, name='instructordashboard'),
    path('instructorviewprofile', views.instructorviewprofile, name='instructorviewprofile'),
    path('instructorchangepassword', views.instructorchangepassword, name='instructorchangepassword'),
    path('instructorallotedstudents', views.instructorallotedstudents, name='instructorallotedstudents'),
    path('instructorviewfeedback', views.instructorviewfeedback, name='instructorviewfeedback'),
    path('instructorupdate', views.instructorupdate, name='instructorupdate'),
    path('addvideo', views.addvideo, name='addvideo'),




    path('course_cancel/<int:course_id>', views.Course_cancel, name='course_cancel'),

    path('product', views.product, name='product'),
    path('singleproduct/<int:id>/', views.singleproduct, name='singleproduct'),
    path('cart/', views.cart, name='cart'),

    path('addcart/<int:id>/', views.addcart, name='addcart'),
    path('de_cart/<int:id>/', views.de_cart, name='de_cart'),
    path('plusqty/<int:id>/', views.plusqty, name='plusqty'),
    path('minusqty/<int:id>/', views.minusqty, name='minusqty'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment_done/', views.payment_done, name='payment_done'),
    path('orders/', views.orders, name='orders'),
    path('search/', views.search, name='search'),


    path('delivery_address/', views.delivery_address, name='delivery_address'),
    path('delivery_address/<int:pk>/', views.delivery_address, name='edit_delivery_address'),
    path('add_wishlist/<int:id>/',views.add_wishlist,name='add_wishlist'),
    path('view_wishlist',views.view_wishlist,name='view_wishlist'),
    path('de_wishlist/<int:id>/',views.de_wishlist,name='de_wishlist'),
    path('delete-video/<int:video_id>/', views.delete_video, name='delete_video'),


]

yogastudio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('login/admin/', admin.site.urls),
    path('', include('yogaapp.urls')),
    path('search/', include('search_app.urls')),
    path('', include('posecollection.urls')),
    path('', include('chat.urls')),
    path('', include('schedule.urls')),

]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/allotcourse.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />

    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">




  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-FgnoXNqdJpWUC0jOBnhiwDLYg+t84xTmT7I/0jUQQCE6U9tnqqluA7miDfBwOdV7" crossorigin="anonymous">


    <title>YOGASTUDIO</title>
	<!-- BOOTSTRAP STYLES-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
     <!-- GOOGLE FONTS-->
   <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel='stylesheet' type='text/css' />
      <script src="{% static 'js/sample_validations.js' %}"></script>
    <style type="text/css">
            table{

            width: 90%;
            padding: 12px;
            border-radius: 4px;
            resize: vertical;
            color: black;
            font-style: bold;
            font-family:Calibri;

            font-size: 20px;
        }
        th{
            width: 20%;
            padding: 12px;
            border-radius: 4px;
            resize: vertical;
            color: black;
            font-style: bold;
            font-family:Calibri;
            font-size: 20px;
        }
        tr{
          width: 90%;
            padding: 12px;
            border-radius: 4px;
            resize: vertical;
            color: black;
            font-style: bold;
            font-family:Calibri;
            font-size: 20px;
        }
        td{
          width: 90%;
            padding: 12px;
            border-radius: 4px;
            resize: vertical;
            color: black;
            font-style: bold;
            font-family:Calibri;
            font-size: 20px;

        }
        textarea{
            width: 40%;
            padding: 12px;
            border-radius: 4px;
            resize: vertical;
            color: black;
            font-style: bold;
            font-family:Calibri;
            font-size: 20px;

        }
        input[type=text]{
            width: 40%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }
       select{
            width: 40%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }
        input[type=password]{
            width:40%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;

        }
        input[type=email]{
            width: 40%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;

        }

        input[type=submit]
        {
            width: 20%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
        }

        .table-card {

       width:70%;
       margin: 0 auto; /* Added */
float: none; /* Added */
margin-bottom: 10px; /* Added */
margin-top:120px;


      background: white;
      border-radius: 2px;

      box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
    }

    .table-card .header {
      line-height: 64px;
      padding-left: 24px;
      padding-right: 14px;
    }

    .table-card .header .title {
      font-size: 20px;
    }

    .table-card .header .actions {
      float: right;
    }

    .table-card .header .actions a {
      color: rgba(0, 0, 0, 0.54);
      font-size: 24px;
      padding-left: 24px;
    }

    .table-card .table {
      padding: 0;
      margin: 0;
    }

    .table-card .table table,
    .table-card .table table tr,
    .table-card .table table > thead > tr > th,
    .table-card .table table > tbody > tr > td {
      padding: 0;
      margin: 0;
    }

    .table-card .table table > thead > tr > th {
      line-height: 56px;
      color: rgba(0, 0, 0, 0.54)
    }

    .table-card .table table > tbody > tr > td {
      line-height: 48px;
      word-wrap: break-word;
    }

    .table-card .table table > thead > tr > th:first-child,
    .table-card .table table > tbody > tr > td:first-child {
      padding-left: 50px;
    }

    .table-card .table table > thead > tr > th:last-child,
    .table-card .table table > tbody > tr > td:last-child {
      padding-right: 5px;
    }
.vl {
  border-left: 6px solid green;
  height: 500px;
}
.profile-pic {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  overflow: hidden;
}

.profile-pic img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
a.live-dot::before {
    content: '';
    display: inline-block;
    width: 10px;
    height: 10px;
    background-color: red;
    border-radius: 50%;
    margin-right: 5px;

}


    </style>


</head>
<body>



    <div id="wrapper">
         <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="adjust-nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color: green; font-size: 30px;"></i>&nbsp;YOGASTUDIO</a>


                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
<li><a  class="live-dot" style="color:green;">{{course.course}}</a></li>

                    <li class="profile-pic">
                            <img src="{{ins.instructor_image.url}}">
                        </li>
                        <li>
                        <a style="color: green;"> {{ins.first_name}}</a></li>
                        <li><a href="{% url 'yogaapp:logout' %}"  style="color: green;">Logout</a></li>
                    </ul>
                </div>

            </div>
        </div>
        <!-- /. NAV TOP  -->

        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu" >

                    <li>
                        <a style="color: green;" href= "{% url 'yogaapp:instructordashboard' %}" ><i class="fa fa-desktop "></i>Instructor Dashboard<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">

<li>
                                <a href= "{% url 'yogaapp:instructorviewprofile' %}" style="color: green;">Profile</a>
                                <a href= "{% url 'yogaapp:instructorchangepassword' %}" style="color: green;">Change Password</a>
                            </li></ul>
                    </li>


                                       <li>
                    <a href= "{% url 'yogaapp:instructorallotedstudents' %}" style="color: green;"><i class="fa fa-sitemap "></i>Course Details</a>

                    </li>






                        <li><a href="{% url 'schedule:allotclass' c_slug=course.slug %}" style="color: green;"><i class="fa fa-clock-o "></i>Schedule a Class</a></li>
                                                <li><a href="{% url 'schedule:coursedetails' c_slug=course.slug %}" style="color: green;"><i class="fa fa-dashboard "></i>View Live Session</a></li>

<li>
                        <a href="{% url 'schedule:course_dates' course.id %}" style="color: green;"><i class="fa fa-desktop "></i>Attendance Records </a>
                    </li>



                      <li>
                        <a href="{% url 'yogaapp:addvideo' %}" style="color: green;"><i class="fa fa-desktop "></i>Add Videos </a>
                    </li>
                     <li>
                        <a href="{% url 'posecollection:capture_pose' %}" style="color: green;"><i class="fa fa-camera"></i>Add Pose</a>
                    </li>
                     <li>
                        <a href="{% url 'yogaapp:instructorviewfeedback' %}" style="color: green;"><i class="fa fa-edit "></i>Feedbacks </a>
                    </li>


                </ul>

            </div>

        </nav>

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
  <h1>Allot Class to {{ course.course }}</h1><hr>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Allot Class">
  </form>

                    </div>
                </div>
                  <hr />

                 <!-- /. ROW  -->
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>

    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="{% static 'js/jquery.metisMenu.js' %}"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="{% static 'js/custom.js' %}"></script>


</body>
</html>

templates/attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Take Attendance for {{ class_schedule.course }}</h1>

<form method="post">
  {% csrf_token %}
  <table>
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Attendance</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td>{{ student }}</td>
<td><input type="checkbox" name="{{ student.id }}" {% if student_attendance|get:student.id|default_if_none:'' %}checked{% endif %}></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <button type="submit">Save Attendance</button>
</form>

</body>
</html>

templates/attendance_graph.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Attendance Graph</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
			margin: 0;
			padding: 0;
		}

		h1 {
			text-align: center;
			margin: 30px 0;
		}

		img {
			display: block;
			margin: 0 auto;
			max-width: 100%;
			height: auto;
		}
		#attendance-graph .present {
      fill: green;
    }
    /* Style for absent dots */
    #attendance-graph .absent {
      fill: red;
    }
    /* Style for legend */
    #legend {
      display: flex;
      align-items: center;
      margin-left:1100px;
      margin-bottom:10px;
    }
    #legend div {
      width: 10px;
      height: 10px;
      margin-right: 5px;
    }
    .present-dot {
      background-color: green;
    }
    .absent-dot {
      background-color: red;
	</style>
</head>
<h6><a href="{{course.get_course_url}}" style="color:blue;font-size:15px;text-decoration:none;margin-left:100px;">&#8592; Back</a></h6>

<body>
	<h1>Attendance Graph Of {{course.course}}</h1>
	<div id="legend">
    <div class="present-dot"></div>
    <span>Present&nbsp;</span>
    <div class="absent-dot"></div>
    <span>Absent</span>
  </div>
	<img src="{% static graph_filename %}">
</body>
</html>

templates/course_students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Students in {{ course.course }}</h1>
<ul>
{% for student in students %}
    <li>{{ student.first_name }}</li>
{% empty %}
    <li>No students found.</li>
{% endfor %}
</ul>

</body>
</html>

templates/instructorassignedstudents.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />

    <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">




  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <title>YOGASTUDIO</title>
	<!-- BOOTSTRAP STYLES-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" />
     <!-- GOOGLE FONTS-->
   <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel='stylesheet' type='text/css' />
    <script src="{% static 'js/sample_validations.js' %}"></script>
<style>
.table-card {

       width:100%;


      background: white;
      border-radius: 2px;

      box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
    }

    .table-card .header {
      line-height: 64px;
      padding-left: 24px;
      padding-right: 14px;
    }

    .table-card .header .title {
      font-size: 20px;
    }

    .table-card .header .actions {
      float: right;
    }

    .table-card .header .actions a {
      color: rgba(0, 0, 0, 0.54);
      font-size: 24px;
      padding-left: 24px;
    }

    .table-card .table {
      padding: 0;
      margin: 0;
    }
 .table-card .header {
      line-height: 64px;
      padding-left: 24px;
      padding-right: 14px;
    }

    .table-card .header .title {
      font-size: 20px;
    }

    .table-card .header .actions {
      float: right;
    }

    .table-card .header .actions a {
      color: rgba(0, 0, 0, 0.54);
      font-size: 24px;
      padding-left: 24px;
    }

    .table-card .table {
      padding: 0;
      margin: 0;
    }

    .table-card .table table,
    .table-card .table table tr,
    .table-card .table table > thead > tr > th,
    .table-card .table table > tbody > tr > td {
      padding: 0;
      margin: 0;
    }

    .table-card .table table > thead > tr > th {
      line-height: 56px;
      color: rgba(0, 0, 0, 0.54)
    }

    .table-card .table table > tbody > tr > td {
      line-height: 48px;
      word-wrap: break-word;
    }

    .table-card .table table > thead > tr > th:first-child,
    .table-card .table table > tbody > tr > td:first-child {
      padding-left: 50px;
    }

    .table-card .table table > thead > tr > th:last-child,
    .table-card .table table > tbody > tr > td:last-child {
      padding-right: 5px;
    }

    }
.vl {
  border-left: 6px solid green;
  height: 500px;
}
.profile-pic {
  width: 30px;
  height: 30px;
  border-radius: 50%;
  overflow: hidden;
}

.profile-pic img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
a.live-dot::before {
    content: '';
    display: inline-block;
    width: 10px;
    height: 10px;
    background-color: red;
    border-radius: 50%;
    margin-right: 5px;

}


</style>

</head>
<body>



    <div id="wrapper">
         <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="adjust-nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="color: green; font-size: 30px;"></i>&nbsp;YOGASTUDIO</a>


                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a  class="live-dot" style="color:green;">{{course.course}}</a></li>

 <li class="profile-pic">
                            <img src="{{ins.instructor_image.url}}">

                        </li>
                        <li>
                        <a style="color: green;"> {{ins.first_name}}</a></li>




                        <li><a href="{% url 'yogaapp:logout' %}"  style="color: green;">Logout</a></li>
                    </ul>
                </div>

            </div>
        </div>
        <!-- /. NAV TOP  -->

        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu" >

                    <li>
                        <a style="color: green;" href= "{% url 'yogaapp:instructordashboard' %}"><i class="fa fa-desktop "></i>Instructor Dashboard<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">

<li>
                                <a href= "{% url 'yogaapp:instructorviewprofile' %}" style="color: green;">Profile</a>
                                <a href= "{% url 'yogaapp:instructorchangepassword' %}" style="color: green;">Change Password</a>
                            </li></ul>
                    </li>





                            <li>
                    <a href= "{% url 'yogaapp:instructorallotedstudents' %}" style="color: green;"><i class="fa fa-sitemap "></i>Course Details</a>



<li><a href="{% url 'schedule:allotclass' c_slug=course.slug %}" style="color: green;"><i class="fa fa-clock-o "></i>Schedule a Class</a></li>
                                                <li><a href="{% url 'schedule:coursedetails' c_slug=course.slug %}" style="color: green;"><i class="fa fa-dashboard "></i>View Live Session</a></li>



<li>
                        <a href="{% url 'schedule:course_dates' course.id %}" style="color: green;"><i class="fa fa-desktop "></i>Attendance Records </a>
                    </li>



                      <li>
                        <a href="{% url 'yogaapp:addvideo' %}" style="color: green;"><i class="fa fa-desktop "></i>Add Videos </a>
                    </li>
 <li>
                        <a href="{% url 'posecollection:capture_pose' %}" style="color: green;"><i class="fa fa-camera"></i>Add Pose</a>
                    </li>
 <li>
                        <a href="{% url 'yogaapp:instructorviewfeedback' %}" style="color: green;"><i class="fa fa-edit "></i>Feedbacks </a>
                    </li>
                </ul>

            </div>

        </nav>

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">












        <div class="table-card p-2 flex" >
          <div class="header">
            <span class="title">Alloted Course</span><hr/>

          </div>
          <div class="table">
            <table class="bordered" >

<tr>
            <td><img src="{{course.course_image.url}}" alt=""  style="width:300px;height:250px;margin-bottom:200px;"></td>
            <td style="padding-left:25px;margin-top:100px;">
                <b style="font-size:25px;"><a href="{% url 'yogaapp:instructorviewvideos' %}">{{course.course}}</a></b>
                <p class="description">{{course.desc}}</p>

                <b>Start Date:</b>&nbsp; &nbsp;{{course.start_date}}<br>
                {% if course.end_date %}
                    <b>Expected End Date:</b>&nbsp;&nbsp; {{course.end_date}}{% endif %}<br>
                    <b>Course Duration:</b>{{course.duration}}<br>
                    <b>Amount: </b>{{course.amount}}<br>
                    <b>Status of the Course:</b>&nbsp;{{course.status}}<br>

            </td>
        </tr>


              </tbody>
            </table>
          </div>

                      <div class="header">
                          <hr/>
            <span class="title">Alloted Students</span><hr/>

          </div>

          <div class="table">
              {% for i in std %}
            <table class="bordered" >

              <tbody>
                <tr>

                  <td>{{i.first_name}}&nbsp;{{i.last_name}}&nbsp;</td>

                    <td><h6>[Contact Number:&nbsp;</h6></td>

                  <td style="color:green;">{{i.phone}}]</td>

                </tr>

                <tr>


                </tr>
    </tbody>
            </table>
{% endfor %}
          </div>

        </div>

      </div><div class="vl"></div>
    </div>

  </div>

</div>
                    </div>
                </div>
                  <hr />

                 <!-- /. ROW  -->
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>

     <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="{% static 'js/jquery.metisMenu.js' %}"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="{% static 'js/custom.js' %}"></script>


</body>
</html>

templates/password_reset.html
{% autoescape off %}


 Hello {{ name }}!!
 Please confirm your email by clicking on the following link.

 Confirmation Link: http://{{ domain }}{% url 'yogaapp:password_reset' uidb64=uid token=token %}

 {% endautoescape %}